services:
  kkmlsfi-novascotia-app:
    container_name: kkmlsfi-novascotia-app-container
    build: .
    image: kkmlsfi-novascotia-app:v1
    ports:
      - "4200:80"
    expose:
      - 4200
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge