// <auto-generated />
using System;
using Kkmlsfi_ns.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kkmlsfi_ns.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241001195732_AddMembersAttendanceTithesAndOfferings")]
    partial class AddMembersAttendanceTithesAndOfferings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalizedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinalizedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemovedFromView")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.Homecell", b =>
                {
                    b.Property<int>("HomecellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomecellId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HomecellDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemovedFromView")
                        .HasColumnType("bit");

                    b.Property<int>("OpeningPrayerMemberId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceMemberId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherMemberId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("HomecellId");

                    b.HasIndex("OpeningPrayerMemberId");

                    b.HasIndex("PlaceMemberId");

                    b.HasIndex("TeacherMemberId");

                    b.ToTable("Homecells");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.HomecellPraiseAndWorshipMember", b =>
                {
                    b.Property<int>("HomecellPraiseAndWorshipMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomecellPraiseAndWorshipMemberId"));

                    b.Property<int>("HomecellId")
                        .HasColumnType("int");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemovedFromView")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("HomecellPraiseAndWorshipMemberId");

                    b.HasIndex("HomecellId");

                    b.HasIndex("MemberId");

                    b.ToTable("HomecellPraiseAndWorshipMembers");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemovedFromView")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.MemberDisplayPicture", b =>
                {
                    b.Property<int>("MemberDisplayPictureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberDisplayPictureID"));

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemovedFromView")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberDisplayPictureID");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberDisplayPictures");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.MembersAttendance", b =>
                {
                    b.Property<int>("MembersAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembersAttendanceId"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<double>("BuildingFund")
                        .HasColumnType("float");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemovedFromView")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<double>("Mission")
                        .HasColumnType("float");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Offering")
                        .HasColumnType("float");

                    b.Property<double>("Others")
                        .HasColumnType("float");

                    b.Property<double>("Tithe")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MembersAttendanceId");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("MemberId");

                    b.ToTable("MembersAttendances");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.Homecell", b =>
                {
                    b.HasOne("Kkmlsfi_ns.API.Models.Domain.Member", "OpeningPrayerMember")
                        .WithMany()
                        .HasForeignKey("OpeningPrayerMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kkmlsfi_ns.API.Models.Domain.Member", "PlaceMember")
                        .WithMany()
                        .HasForeignKey("PlaceMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kkmlsfi_ns.API.Models.Domain.Member", "TeacherMember")
                        .WithMany()
                        .HasForeignKey("TeacherMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpeningPrayerMember");

                    b.Navigation("PlaceMember");

                    b.Navigation("TeacherMember");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.HomecellPraiseAndWorshipMember", b =>
                {
                    b.HasOne("Kkmlsfi_ns.API.Models.Domain.Homecell", "Homecell")
                        .WithMany("HomecellPraiseAndWorshipMembers")
                        .HasForeignKey("HomecellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kkmlsfi_ns.API.Models.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Homecell");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.MemberDisplayPicture", b =>
                {
                    b.HasOne("Kkmlsfi_ns.API.Models.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.MembersAttendance", b =>
                {
                    b.HasOne("Kkmlsfi_ns.API.Models.Domain.Attendance", "Attendance")
                        .WithMany("MembersAttendances")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kkmlsfi_ns.API.Models.Domain.Member", "Member")
                        .WithMany("MembersAttendances")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.Attendance", b =>
                {
                    b.Navigation("MembersAttendances");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.Homecell", b =>
                {
                    b.Navigation("HomecellPraiseAndWorshipMembers");
                });

            modelBuilder.Entity("Kkmlsfi_ns.API.Models.Domain.Member", b =>
                {
                    b.Navigation("MembersAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
